"""Create initial schema

Revision ID: 0c50a272d1a4
Revises: 
Create Date: 2026-06-25 15:52:08.101976

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c50a272d1a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_configs_channel'), 'channel_configs', ['channel'], unique=True)
    op.create_table('notification_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_types_code'), 'notification_types', ['code'], unique=True)
    op.create_table('notification_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_type_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('subject_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('required_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel_configs.id'], ),
    sa.ForeignKeyConstraint(['notification_type_id'], ['notification_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_type_id', 'channel_id', name='uniq_notification_template_type_channel')
    )
    op.create_index(op.f('ix_notification_templates_channel_id'), 'notification_templates', ['channel_id'], unique=False)
    op.create_table('notification_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_service', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notification_type_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rendered_subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rendered_body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_msg', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notification_type_id'], ['notification_types.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_requests_channel'), 'notification_requests', ['channel'], unique=False)
    op.create_index(op.f('ix_notification_requests_recipient'), 'notification_requests', ['recipient'], unique=False)
    op.create_index(op.f('ix_notification_requests_status'), 'notification_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_requests_status'), table_name='notification_requests')
    op.drop_index(op.f('ix_notification_requests_recipient'), table_name='notification_requests')
    op.drop_index(op.f('ix_notification_requests_channel'), table_name='notification_requests')
    op.drop_table('notification_requests')
    op.drop_index(op.f('ix_notification_templates_channel_id'), table_name='notification_templates')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_notification_types_code'), table_name='notification_types')
    op.drop_table('notification_types')
    op.drop_index(op.f('ix_channel_configs_channel'), table_name='channel_configs')
    op.drop_table('channel_configs')
    # ### end Alembic commands ###
